backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - name: 'video'
    label: 'Vidéos'
    folder: 'content/videos'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Ordre (le plus élevé en premier)', name: 'order', widget: 'number' }
      - { label: "Vidéo (seulement l'id)", name: 'video', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'atelier'
    label: "Ateliers"
    folder: "content/ateliers"
    format: "frontmatter"
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string',required: false }
      - { label: 'Image', name: 'image', widget: 'image',required: false}
      - { label: "Texte alternatif de l'image", name: 'imageAlt', widget: 'string',required: false}
      - { label: "URL d'achat (podia)", name: 'buyUrl', widget: 'string',required: false }
      - { label: "Prix", name: 'price', widget: 'number',required: false }
      - { label: "Promotion", name: 'promo', widget: 'number',required: false }
      - { label: "Couleur du texte de l'entête", name: 'colorText', widget: 'string',default: "white",required: false }
      - { label: "Couleur fond 1", name: 'colorBg1', widget: 'string',required: false }
      - { label: "Couleur fond 2", name: 'colorBg2', widget: 'string',required: false }
      - { label: 'Ordre (le plus élevé en premier)', name: 'order', widget: 'number',required: false }
      - { label: 'Contenu', name: 'body', widget: 'markdown',required: false }

  - name: 'page'
    label: "Pages"
    folder: "content/"
    format: "frontmatter"
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string',required: false }
      - { label: 'Logo', name: 'logo', widget: 'image', media_folder: "static/logos",required: false}
      - { label: "Couleur du texte de l'entête", name: 'colorText', widget: 'string',default: "white",required: false }
      - { label: "Couleur fond 1", name: 'colorBg1', widget: 'string',required: false }
      - { label: "Couleur fond 2", name: 'colorBg2', widget: 'string',required: false }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }

  - name: "config"
    label: "Configuration"
    folder: "content/general.json"
    format: "json"
    create: false
    fields:
      - { label : "Nom du site", name: "SiteName",widget: "string" }
